In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'Age' : [25,23,59,66,12],
    'Salary':[25,66,99,88,14],
    'Height':[150,170,180,159,123],
    'Weight':[98,58,45,75,95],
    'Gender':['M','M','F','F','M']
}

In [3]:
data

{'Age': [25, 23, 59, 66, 12],
 'Salary': [25, 66, 99, 88, 14],
 'Height': [150, 170, 180, 159, 123],
 'Weight': [98, 58, 45, 75, 95],
 'Gender': ['M', 'M', 'F', 'F', 'M']}

In [8]:
df = pd.DataFrame(data,index=['Rahul','Sudhir','Shena','Neha','Hari'])

In [9]:
df

        Age  Salary  Height  Weight Gender
Rahul    25      25     150      98      M
Sudhir   23      66     170      58      M
Shena    59      99     180      45      F
Neha     66      88     159      75      F
Hari     12      14     123      95      M

In [10]:
df

        Age  Salary  Height  Weight Gender
Rahul    25      25     150      98      M
Sudhir   23      66     170      58      M
Shena    59      99     180      45      F
Neha     66      88     159      75      F
Hari     12      14     123      95      M