In [ ]:
import pandas as pd
import numpy as np

#Pandas Series

In [ ]:
data = np.asarray(['A','B','C',"D","E"])

In [ ]:
data

array(['A', 'B', 'C', 'D', 'E'], dtype='<U1')

In [ ]:
s1 = pd.Series(data)
print(s1)

0    A
1    B
2    C
3    D
4    E
dtype: object

In [ ]:
s1 = pd.Series(data,index= [101,102,103,104,105])
print(s1)

101    A
102    B
103    C
104    D
105    E
dtype: object

In [ ]:
#Create series from dictionary
data = {"a":1,"b":2,"c":3}
s2 = pd.Series(data)
print(s2)

a    1
b    2
c    3
dtype: int64

In [ ]:
#Create series from dictionary
data = {"a":1,"b":2,"c":3}
s2 = pd.Series(data,index=['a','b','c','d'])
print(s2)

a    1.0
b    2.0
c    3.0
d    NaN
dtype: float64

In [ ]:
#Creating series using a scalar
s3 = pd.Series(7,index=[0,1,2,3,4])
print(s3)

0    7
1    7
2    7
3    7
4    7
dtype: int64

In [ ]:
#Accessing Data in series
s4 = pd.Series([1,2,3,5,6],index=["E","B","D","T","U"])
print(s4)

E    1
B    2
D    3
T    5
U    6
dtype: int64

In [ ]:
type(s4[4])

numpy.int64

In [ ]:
type(s4[-2:])

pandas.core.series.Series

In [ ]:
s4['E']

1

In [ ]:
#Exploring and analyzing a Series
s4

E    1
B    2
D    3
T    5
U    6
dtype: int64

In [ ]:
s4.mean()

3.4

In [ ]:
s4.max()

6

In [ ]:
s4.min()

1

In [ ]:
s4.std()

2.0736441353327724

In [ ]:
s4.describe()

count    5.000000
mean     3.400000
std      2.073644
min      1.000000
25%      2.000000
50%      3.000000
75%      5.000000
max      6.000000
dtype: float64

In [ ]:
#Create series from dictionary
data = {"Saurav":"Kritipur","Prakash":"Sundarijal","Sandesh":"Thankot"}
s2 = pd.Series(data)
print(s2)

Saurav       Kritipur
Prakash    Sundarijal
Sandesh       Thankot
dtype: object

In [ ]:
s2.describe()

count            3
unique           3
top       Kritipur
freq             1
dtype: object

#DataFrame in Pandas

In [ ]:
Math = pd.Series([10,20,30,40],
                 index= ["Saurav","Prakash","Sandesh","Bibek"])
Compiler = pd.Series([20,22,32,46],
                 index= ["Saurav","Prakash","Sandesh","Bibek"])
SE = pd.Series([60,88,99,15],
                 index= ["Saurav","Prakash","Sandesh","Bibek"])
E_gov = pd.Series([11,20,50,40,69],
                 index= ["Amrit","Saurav","Prakash","Sandesh","Bibek"])

In [ ]:
marks = {"Math":Math,"Compiler":Compiler,"SE":SE,"E Gov":E_gov}

In [ ]:
df = pd.DataFrame(marks)

In [ ]:
df

         Math  Compiler    SE  E Gov
Amrit     NaN       NaN   NaN     11
Bibek    40.0      46.0  15.0     69
Prakash  20.0      22.0  88.0     50
Sandesh  30.0      32.0  99.0     40
Saurav   10.0      20.0  60.0     20

In [ ]:
df2 = pd.DataFrame(marks,index = ["Bibek","Sandesh","Prakash"])
print(df2)

In [ ]:
df3 = pd.DataFrame(marks,index = ["Bibek","Sandesh","Prakash"],
                   columns=['Math',"Compiler"])
print(df3)

         Math  Compiler
Bibek      40        46
Sandesh    30        32
Prakash    20        22

In [ ]:
df3 = pd.DataFrame(marks,index = ["Bibek","Sandesh","Prakash","Dipesh"],
                   columns=['Math',"Compiler"])
print(df3)

In [ ]:
df3 = pd.DataFrame(marks,index = ["Bibek","Sandesh","Prakash","Dipesh"],
                   columns=['Math',"Compiler","TOC"])
print(df3)

In [ ]:
dict_a = {"Math":[10,22,33],"Compiler":[88,99,66],"SE":[88,44,55]}
df = pd.DataFrame(dict_a)
df

   Math  Compiler  SE
0    10        88  88
1    22        99  44
2    33        66  55

In [ ]:
dict_a = {"Math":[10,22,33],"Compiler":[88,99,66],"SE":[88,44,55]}
df = pd.DataFrame(dict_a,index=["Saurav","Prakash","Sandesh"])
df

         Math  Compiler  SE
Saurav     10        88  88
Prakash    22        99  44
Sandesh    33        66  55

In [ ]:
#Creating dataframes from list of Dictionaries
data = [{'Math':1,"C":55,"OOP":22},
        {"Math":15,"C":78,"OOP":82}]

In [ ]:
df = pd.DataFrame(data)
df

In [ ]:
#Creating DataFrames from a Dict of Tuples
dic_a = {"Maths":(1,55,22,66),"C":(88,99,66,33),"OOP":(88,99,12,56)}
df = pd.DataFrame(dic_a)
df

In [ ]:
#Dataframe from list of tuples
marks = [(1,2,3,5),(7,8,9,5),(4,5,6,22)]
df= pd.DataFrame(marks)
df

   0  1  2   3
0  1  2  3   5
1  7  8  9   5
2  4  5  6  22

In [ ]:
df= pd.DataFrame(marks,index=['A','V','B'],columns = ["M","A","T","G"])
df

   M  A  T   G
A  1  2  3   5
V  7  8  9   5
B  4  5  6  22

#Selecting, adding and deleting data in datafrme

In [ ]:
expense= {'Food':[55,66,88,99,55],
          "Travel":[77,88,99,12,63],
          "Rent":[77,54,12,63,96]}

In [ ]:
df = pd.DataFrame(expense)
df

In [ ]:
df['Total'] = df['Food']+df['Travel']+df['Rent']
df

In [ ]:
df["Flag"] =df["Total"] > 200
df

In [ ]:
df["Random"] = "ABC"
df

In [ ]:
random = df.pop('Random')
df

In [ ]:
random

In [ ]:
del df['Rent']
df

   Food  Travel  Total   Flag
0    55      77    209   True
1    66      88    208   True
2    88      99    199  False
3    99      12    174  False
4    55      63    214   True

In [ ]:
df.insert(0,'Education',[5,88,99,66,33])
df

In [ ]:
df.insert(2,"Income",[88,152,123,456,748])
df

In [ ]:
df = df.assign(Net = lambda x : x['Total']-x['Income'])
df

#Indexing and selecting data frames

In [ ]:
df

   Education  Food  Income  Travel  Total   Flag  Net
0          5    55      88      77    209   True  121
1         88    66     152      88    208   True   56
2         99    88     123      99    199  False   76
3         66    99     456      12    174  False -282
4         33    55     748      63    214   True -534

In [ ]:
df["Food"]

In [ ]:
df.iloc[2]

Education       99
Food            88
Income         123
Travel          99
Total          199
Flag         False
Net             76
Name: 2, dtype: object

In [ ]:
df[2:]

   Education  Food  Income  Travel  Total   Flag  Net
2         99    88     123      99    199  False   76
3         66    99     456      12    174  False -282
4         33    55     748      63    214   True -534

In [ ]:
df[df["Food"]>60]

   Education  Food  Income  Travel  Total   Flag  Net
1         88    66     152      88    208   True   56
2         99    88     123      99    199  False   76
3         66    99     456      12    174  False -282