#Imports

In [1]:
import pandas as pd
import numpy as np

#Checking and handling missing values

In [4]:
df = pd.DataFrame(np.random.randn(5,3),index=["a","c","e","g","h"],
                  columns=["Stock1","Stock2","Stock3"])

In [ ]:
df

In [8]:
df = df.reindex(["a","b","c","d","e","f","g","h"])
df

     Stock1    Stock2    Stock3
a  0.145549  1.988204 -1.300210
b       NaN       NaN       NaN
c -0.402532  0.049567  0.444323
d       NaN       NaN       NaN
e  1.329487 -0.828810 -0.301236
f       NaN       NaN       NaN
g  2.046290 -1.538654 -0.726795
h -0.686865 -0.872345  2.164815

In [ ]:
df.isnull()

In [12]:
df

     Stock1    Stock2    Stock3
a  0.145549  1.988204 -1.300210
b       NaN       NaN       NaN
c -0.402532  0.049567  0.444323
d       NaN       NaN       NaN
e  1.329487 -0.828810 -0.301236
f       NaN       NaN       NaN
g  2.046290 -1.538654 -0.726795
h -0.686865 -0.872345  2.164815

In [13]:
df.fillna(0)

     Stock1    Stock2    Stock3
a  0.145549  1.988204 -1.300210
b  0.000000  0.000000  0.000000
c -0.402532  0.049567  0.444323
d  0.000000  0.000000  0.000000
e  1.329487 -0.828810 -0.301236
f  0.000000  0.000000  0.000000
g  2.046290 -1.538654 -0.726795
h -0.686865 -0.872345  2.164815

In [14]:
df.fillna(method="pad")

     Stock1    Stock2    Stock3
a  0.145549  1.988204 -1.300210
b  0.145549  1.988204 -1.300210
c -0.402532  0.049567  0.444323
d -0.402532  0.049567  0.444323
e  1.329487 -0.828810 -0.301236
f  1.329487 -0.828810 -0.301236
g  2.046290 -1.538654 -0.726795
h -0.686865 -0.872345  2.164815

In [15]:
df.dropna()

     Stock1    Stock2    Stock3
a  0.145549  1.988204 -1.300210
c -0.402532  0.049567  0.444323
e  1.329487 -0.828810 -0.301236
g  2.046290 -1.538654 -0.726795
h -0.686865 -0.872345  2.164815

In [ ]:
df.replace(np.nan,0)

#Reading and cleaning data

In [17]:
path = "/content/Sales-1.xlsx"
df = pd.read_excel(path)

In [ ]:
df.head()

In [ ]:
df.tail()

In [ ]:
df = pd.read_excel(path,nrows=10)
df

In [ ]:
df = pd.read_excel(path,nrows=10,usecols=[0,1,2,6])
df

In [22]:
df.columns

Index(['SALES_ID', 'SALES_BY_REGION', 'JANUARY', 'MAY'], dtype='object')

In [ ]:
#renaming columns
df.rename(columns={"SALES_ID":"ID","SALES_BY_REGION":"REGION"})

In [ ]:
df

In [26]:
#renaming columns
df.rename(columns={"SALES_ID":"ID","SALES_BY_REGION":"REGION"},inplace=True)

In [28]:
df.head(2)

   ID REGION JANUARY   MAY
0  16    UAQ    n.a.  5433
1  10    FUJ    1085  1951

In [29]:
df["MAY"].unique()

array([5433, 1951, 2194, 1864, 3794, 4383, 5803, 1413,  944, 4513])

In [30]:
df['REGION'].unique()

array(['UAQ', ' FUJ', 'AUH', 'DXB', 'RAK', 'SHJ'], dtype=object)

In [31]:
df

   ID REGION JANUARY   MAY
0  16    UAQ    n.a.  5433
1  10    FUJ    1085  1951
2  28    AUH      -1  2194
3   8    DXB    3490  1864
4   5    FUJ    2152  3794
5  28    RAK    n.a.  4383
6   1    AUH    3469  5803
7   3    SHJ    2473  1413
8  11    SHJ    3736   944
9  20    DXB    1895  4513

In [33]:
df = pd.read_excel(path,nrows=20)
df.head()

,SALES_ID,SALES_BY_REGION,JANUARY,FEBRUARY,MARCH,APRIL,MAY,JUNE,JULY,AUGUST,SEPTEMBER,OCTOBER,NOVEMBER,DECEMBER
0,16,UAQ,n.a.,5941,3487,-1,5433,3511,2555,n.a.,1929,4285,1198,-1
1,10,FUJ,1085,5189,n.a.,1142,1951,3967,1993,5116,3785,2733,5686,n.a.
2,28,AUH,-1,1796,2472,4829,2194,-1,1142,1674,5857,1500,3219,5033
3,8,DXB,3490,not avilable,1317,2351,1864,n.a.,4161,1131,2173,4005,5238,1396
4,5,FUJ,2152,3064,3981,2958,3794,5453,3324,n.a.,1516,5640,1301,5513

In [ ]:
df = pd.read_excel(path,nrows=20,na_values=["n.a.","not avilable"])
df.head()

#Using functions to clean

In [38]:
def CleanData(cell):
  if(cell == 'n.a.' or cell == -1 or cell == "not avilable"):
    return 0
  return cell

In [39]:
def CleanData_Region(cell):
  if(cell == 'n.a.' or cell == -1 or cell == "not avilable"):
    return "AbuDhabi"
  return cell

In [ ]:
df = pd.read_excel(path,nrows=10)
df

In [41]:
df = pd.read_excel(path,nrows=10,
                   converters={"SALES_BY_REGION":CleanData_Region,
                                             "JANUARY":CleanData,
                                             "FEBRUARY":CleanData})
df

,SALES_ID,SALES_BY_REGION,JANUARY,FEBRUARY,MARCH,APRIL,MAY,JUNE,JULY,AUGUST,SEPTEMBER,OCTOBER,NOVEMBER,DECEMBER
0,16,UAQ,0,5941,3487,-1,5433,3511,2555,n.a.,1929,4285,1198,-1
1,10,FUJ,1085,5189,n.a.,1142,1951,3967,1993,5116,3785,2733,5686,n.a.
2,28,AUH,0,1796,2472,4829,2194,-1,1142,1674,5857,1500,3219,5033
3,8,DXB,3490,0,1317,2351,1864,n.a.,4161,1131,2173,4005,5238,1396
4,5,FUJ,2152,3064,3981,2958,3794,5453,3324,n.a.,1516,5640,1301,5513
5,28,RAK,0,5612,5113,5552,4383,3397,3270,4902,2095,n.a.,5708,1864
6,1,AUH,3469,0,not avilable,3642,5803,5662,1896,2293,2583,5233,4421,4071
7,3,SHJ,2473,1421,3606,1314,1413,2091,3270,3346,2080,1539,2630,1697
8,11,SHJ,3736,3164,930,2791,944,4051,2912,3054,2983,994,3465,2643
9,20,DXB,1895,2478,1050,3564,4513,1879,2951,3464,4849,1386,2331,2931

#Merging and Integrating Data

In [42]:
path1 = "/content/1.-Export1_Columns.csv"
path2 = "/content/1.-Export2_Columns.csv"

In [43]:
df1 = pd.read_csv(path1)
df2 = pd.read_csv(path2)

In [ ]:
df1

In [ ]:
df2

In [46]:
#merging
df1 = pd.read_csv(path1,nrows=10)
df2 = pd.read_csv(path2,nrows=10)

In [47]:
df1.head(1)

  Country Name Country Code  2004  2005  2006  2007
0        Benin          BEN   811   940   869  1076

In [48]:
df2.head(2)

   Country Name Country Code  2008  2009  2010  2011  2012  2013  2014
0         Benin          BEN  1312  1039   991  1040  1154  1518  1656
1  Burkina Faso          BFA   834  1063  1727  2681  2849  3166  3551

In [51]:
mergeddf = df1.merge(df2)
mergeddf

,Country Name,Country Code,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014
0,Benin,BEN,811,940,869,1076,1312,1039,991,1040,1154,1518,1656
1,Burkina Faso,BFA,548,532,673,714,834,1063,1727,2681,2849,3166,3551
2,Bangladesh,BGD,7257,9995,11745,13530,16181,17360,18472,25627,26887,29305,34344
3,Bulgaria,BGR,10713,12703,16151,23263,28591,21964,26836,35488,33975,37260,37845
4,Bahrain,BHR,10337,13397,15662,17314,21231,15705,17880,22945,22853,0,0
5,"Bahamas, The",BHS,3161,3482,3558,3888,3797,3117,3223,3443,3733,3715,3739
6,Bosnia and Herzegovina,BIH,3232,3550,4505,4078,4911,4265,4901,5703,5219,5706,0
7,Belarus,BLR,15710,18065,22200,27592,37021,24865,29402,48462,51745,44058,43555
8,Belize,BLZ,535,609,744,788,854,690,813,894,983,988,0
9,Bermuda,BMU,0,0,0,0,0,2699,2705,2644,2589,2657,0

In [50]:
verticalstack = pd.concat((df1,df2),axis=0)
verticalstack

,Country Name,Country Code,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014
0,Benin,BEN,811.0,940.0,869.0,1076.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Burkina Faso,BFA,548.0,532.0,673.0,714.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Bangladesh,BGD,7257.0,9995.0,11745.0,13530.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Bulgaria,BGR,10713.0,12703.0,16151.0,23263.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Bahrain,BHR,10337.0,13397.0,15662.0,17314.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,"Bahamas, The",BHS,3161.0,3482.0,3558.0,3888.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Bosnia and Herzegovina,BIH,3232.0,3550.0,4505.0,4078.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Belarus,BLR,15710.0,18065.0,22200.0,27592.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Belize,BLZ,535.0,609.0,744.0,788.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Bermuda,BMU,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Benin,BEN,NaN,NaN,NaN,NaN,1312.0,1039.0,991.0,1040.0,1154.0,1518.0,1656.0
1,Burkina Faso,BFA,NaN,NaN,NaN,NaN,834.0,1063.0,1727.0,2681.0,2849.0,3166.0,3551.0
2,Bangladesh,BGD,NaN,NaN,NaN,NaN,16181.0,17360.0,18472.0,25627.0,26887.0,29305.0,34344.0
3,Bulgaria,BGR,NaN,NaN,NaN,NaN,28591.0,21964.0,26836.0,35488.0,33975.0,37260.0,37845.0
4,Bahrain,BHR,NaN,NaN,NaN,NaN,21231.0,15705.0,17880.0,22945.0,22853.0,0.0,0.0
5,"Bahamas, The",BHS,NaN,NaN,NaN,NaN,3797.0,3117.0,3223.0,3443.0,3733.0,3715.0,3739.0
6,Bosnia and Herzegovina,BIH,NaN,NaN,NaN,NaN,4911.0,4265.0,4901.0,5703.0,5219.0,5706.0,0.0
7,Belarus,BLR,NaN,NaN,NaN,NaN,37021.0,24865.0,29402.0,48462.0,51745.0,44058.0,43555.0
8,Belize,BLZ,NaN,NaN,NaN,NaN,854.0,690.0,813.0,894.0,983.0,988.0,0.0
9,Bermuda,BMU,NaN,NaN,NaN,NaN,0.0,2699.0,2705.0,2644.0,2589.0,2657.0,0.0

#Exploring and analyzing dataframe

In [53]:
data = {"Age":[30,50,62,30,10,20],
        "Salary":[78,45,12,2,36,54],
        "Height":[120,125,163,147,180,181],
        "Weight":[50,55,52,63,87,89],
        "Gender":["Male","Male","Female","Female","Female","Female"]}

In [ ]:
df = pd.DataFrame(data,index=["Prakash","Sandesh","Durga","Roshan","Pramish","Bibek"])
df

In [ ]:
df.describe(include="all")

In [ ]:
df.Height.describe()

In [ ]:
df["Height"].describe()

In [ ]:
df.describe(include=[np.object])

In [ ]:
df.describe(include=[np.number])

In [ ]:
df.corr()

#Data Grouping

In [62]:
Number = [1,2,3,4,5,6,7,8,9,10]
Names = ["Bibek","Amrit","Sohan","Rohan","Sumit","Sagar","Sahil","Prakash","Prabin","Durga"]
City = ["Dubai","Karachi","Islamabad","Lisbon","Dubai",
        "Berlin","Karachi","Berlin","Berlin","Moscow"]

Gender = ["M","M","M","M","F","F","F","F","F","F"]
Height = [6,7,8,7,5,5,6,7,6.3,7.1]
Weight = [50,54,87,89,54,20,14,58,96,87]

In [63]:
df = pd.DataFrame({"Number":Number,
                   "Name":Names,
                   "City":City,
                   "Gender":Gender,
                   "Height":Height,
                   "Weight":Weight})

In [ ]:
df

In [ ]:
df.groupby("City").count()

In [ ]:
df.groupby(["City","Gender"]).count()

In [68]:
grouped = df.groupby("City")
print(grouped.get_group("Dubai"))

   Number   Name   City Gender  Height  Weight
0       1  Bibek  Dubai      M     6.0      50
4       5  Sumit  Dubai      F     5.0      54

In [ ]:
print(grouped["Height"].agg(np.mean))

In [70]:
print(grouped["Weight"].agg([np.mean,np.sum,np.std]))

           mean  sum        std
City
Berlin     58.0  174  38.000000
Dubai      52.0  104   2.828427
Islamabad  87.0   87        NaN
Karachi    34.0   68  28.284271
Lisbon     89.0   89        NaN
Moscow     87.0   87        NaN

In [71]:
#transforming data
df = df.set_index("Number")
score = lambda x:(x-x.mean())/x.std()*10
print(grouped.transform(score))

      Number     Height     Weight
0  -7.071068   7.071068  -7.071068
1  -7.071068   7.071068   7.071068
2        NaN        NaN        NaN
3        NaN        NaN        NaN
4   7.071068  -7.071068   7.071068
5 -10.910895 -10.838622 -10.000000
6   7.071068  -7.071068  -7.071068
7   2.182179   8.867964   0.000000
8   8.728716   1.970659  10.000000
9        NaN        NaN        NaN

<ipython-input-71-0bcf43637e5c>:4: FutureWarning: Dropping invalid columns in DataFrameGroupBy.transform is deprecated. In a future version, a TypeError will be raised. Before calling .transform, select only columns which should be valid for the function.
  print(grouped.transform(score))