In [1]:
import pandas as pd
import numpy as np

In [2]:
Number = [1,2,3,4,5,6,7,8,9,10]
Names = ["Bibek","Amrit","Sohan","Rohan","Sumit","Sagar","Sahil","Prakash","Prabin","Durga"]
City = ["Dubai","Karachi","Islamabad","Lisbon","Dubai",
        "Berlin","Karachi","Berlin","Berlin","Moscow"]

Gender = ["M","M","M","M","F","F","F","F","F","F"]
Height = [6,7,8,7,5,5,6,7,6.3,7.1]
Weight = [50,54,87,89,54,20,14,58,96,87]

In [3]:
df = pd.DataFrame({"Number":Number,
                   "Name":Names,
                   "City":City,
                   "Gender":Gender,
                   "Height":Height,
                   "Weight":Weight})

In [4]:
df

   Number     Name       City Gender  Height  Weight
0       1    Bibek      Dubai      M     6.0      50
1       2    Amrit    Karachi      M     7.0      54
2       3    Sohan  Islamabad      M     8.0      87
3       4    Rohan     Lisbon      M     7.0      89
4       5    Sumit      Dubai      F     5.0      54
5       6    Sagar     Berlin      F     5.0      20
6       7    Sahil    Karachi      F     6.0      14
7       8  Prakash     Berlin      F     7.0      58
8       9   Prabin     Berlin      F     6.3      96
9      10    Durga     Moscow      F     7.1      87

In [5]:
df.groupby('City').filter(lambda x:len(x)>2)

   Number     Name    City Gender  Height  Weight
5       6    Sagar  Berlin      F     5.0      20
7       8  Prakash  Berlin      F     7.0      58
8       9   Prabin  Berlin      F     6.3      96

In [ ]:
df[(df.Height > 6) & (df.Weight>60)]

In [8]:
df[df.City.str.startswith("M")]

   Number   Name    City Gender  Height  Weight
9      10  Durga  Moscow      F     7.1      87

In [ ]:
df[~df.City.str.startswith("M")]

In [11]:
df.query('City=="Dubai" and Height >5')

   Number   Name   City Gender  Height  Weight
0       1  Bibek  Dubai      M     6.0      50

In [12]:
df.nlargest(3,'Height')

   Number   Name       City Gender  Height  Weight
2       3  Sohan  Islamabad      M     8.0      87
9      10  Durga     Moscow      F     7.1      87
1       2  Amrit    Karachi      M     7.0      54

In [ ]:
df.nsmallest(3,'Height')

In [14]:
df

   Number     Name       City Gender  Height  Weight
0       1    Bibek      Dubai      M     6.0      50
1       2    Amrit    Karachi      M     7.0      54
2       3    Sohan  Islamabad      M     8.0      87
3       4    Rohan     Lisbon      M     7.0      89
4       5    Sumit      Dubai      F     5.0      54
5       6    Sagar     Berlin      F     5.0      20
6       7    Sahil    Karachi      F     6.0      14
7       8  Prakash     Berlin      F     7.0      58
8       9   Prabin     Berlin      F     6.3      96
9      10    Durga     Moscow      F     7.1      87

In [15]:
df.iloc[3:6,1:3]

    Name    City
3  Rohan  Lisbon
4  Sumit   Dubai
5  Sagar  Berlin

In [16]:
df.index = ["a","b","c","d","e","f","g","h","i","j"]

In [ ]:
df

In [ ]:
df.iloc[3:5,:]

In [ ]:
df.loc['a':'e',:]

#Cross tabulation in pandas

In [20]:
path = "/content/jpt.csv"

In [ ]:
df = pd.read_csv(path)
df.tail()

In [25]:
df.columns

Index(['SN', 'Country', 'City', 'Income', 'Expense', 'Gender', 'Language',
       'Movie', 'ELO', 'Cheese'],
      dtype='object')

In [26]:
len(df.columns)

10

In [ ]:
pd.crosstab(index=df.Country,columns=df.Gender)

In [ ]:
pd.crosstab(index=df['Country'],columns=df['Gender'])

In [ ]:
pd.crosstab(df['Country'],df['Gender'])

In [ ]:
pd.crosstab([df['Country'],df['City']],df['Gender'])

In [ ]:
pd.crosstab(df['Country'],[df['Gender'],df['Movie']])

In [ ]:
pd.crosstab([df['Country'],df['City']],[df['Gender'],df['Movie']])

#Selection with .loc and .iloc

In [35]:
pd.crosstab(df['Country'],df['Gender']).loc['Germany']

Gender
F    5
M    9
Name: Germany, dtype: int64

In [ ]:
pd.crosstab([df['Country'],df['City']],df['Gender']).loc['Germany']

In [39]:
pd.crosstab([df['Country'],df['City']],df['Gender']).loc['Germany','Berlin']

Gender
F    0
M    9
Name: (Germany, Berlin), dtype: int64

In [ ]:
pd.crosstab([df['Country'],df['City']],df['Gender']).loc['Berlin']

In [ ]:
pd.crosstab([df['Country'],df['City']],df['Gender']).loc[['Germany','Peru'],['F']]

In [44]:
pd.crosstab([df['Country'],df['City']],[df['Gender'],df['Cheese']]).loc[[('Germany','Berlin'),("Peru","Tacna")]]

Gender          F     M
Cheese          N  Y  N  Y
Country City
Germany Berlin  0  0  0  9
Peru    Tacna   1  1  2  0

In [ ]:
list_of_selection = [('Germany','Berlin'),("Peru","Tacna")]
pd.crosstab([df['Country'],df['City']],[df['Gender'],df['Cheese']]).loc[list_of_selection]

In [48]:
pd.crosstab([df['Country'],df['City']],[df['Gender'],df['Cheese']])

Gender               F     M
Cheese               N  Y  N  Y
Country     City
Afganisthan Kabul    3  1  1  3
            Kandhar  3  1  1  0
Germany     Berlin   0  0  0  9
            Munich   3  1  0  0
Peru        Cusco    1  1  0  0
            Lima     1  0  3  2
            Tacna    1  1  2  0
Somalia     Bura     1  0  3  2
            Marka    3  1  0  0

In [50]:
pd.crosstab([df['Country'],df['City']],[df['Gender'],df['Cheese']]).iloc[:3]

Gender               F     M
Cheese               N  Y  N  Y
Country     City
Afganisthan Kabul    3  1  1  3
            Kandhar  3  1  1  0
Germany     Berlin   0  0  0  9

#using basic function with crosstab

In [54]:
pd.crosstab([df.City],[df.Gender]).loc[['Kabul','Lima',"Marka"]].max()

Gender
F    4
M    5
dtype: int64

In [ ]:
#margins are for total
pd.crosstab([df.City],[df.Gender],margins=True)

In [56]:
#normalizing results
pd.crosstab([df.Country],[df.Gender],normalize=True)

Gender          F     M
Country
Afganisthan  0.16  0.10
Germany      0.10  0.18
Peru         0.12  0.14
Somalia      0.10  0.10

In [57]:
pd.crosstab([df.Country],[df.Gender],normalize="index")

Gender              F         M
Country
Afganisthan  0.615385  0.384615
Germany      0.357143  0.642857
Peru         0.461538  0.538462
Somalia      0.500000  0.500000

In [ ]:
pd.crosstab([df['Country'],df['City']],[df.Gender],normalize="columns")

#Aggregrate function

In [ ]:
df

In [ ]:
pd.crosstab([df['Country']],[df.Gender],values=df.ELO,aggfunc='sum')

#unique values

In [ ]:
pd.crosstab(df.Country,df.Movie).nunique(axis=1)