#Introduction

In [1]:
import pandas as pd
import numpy as np

In [2]:
#Introduction
print("Pandas Version: ",pd.__version__)

Pandas Version:  2.0.3

#Basic Series

In [3]:
# Series
print("\n--- Series ---")
series = pd.Series([1, 3, 5, np.nan, 6, 8])
print(series)

--- Series ---
0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [4]:
series

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

# DataFrame

In [5]:
print("\n--- DataFrame ---")
data = {
    'A': 1.,
    'B': pd.Timestamp('20230101'),
    'C': pd.Series(1, index=list(range(4)), dtype='float32'),
    'D': np.array([3] * 4, dtype='int32'),
    'E': pd.Categorical(["test", "train", "test", "train"]),
    'F': 'foo'
}
df = pd.DataFrame(data)
print(df)

--- DataFrame ---
     A          B    C  D      E    F
0  1.0 2023-01-01  1.0  3   test  foo
1  1.0 2023-01-01  1.0  3  train  foo
2  1.0 2023-01-01  1.0  3   test  foo
3  1.0 2023-01-01  1.0  3  train  foo

#Data manipulation

In [7]:
# Indexing and Selection
print("\n--- Indexing and Selection ---")
print(df['A'])

--- Indexing and Selection ---
0    1.0
1    1.0
2    1.0
3    1.0
Name: A, dtype: float64

In [8]:
print(df[0:2])

     A          B    C  D      E    F
0  1.0 2023-01-01  1.0  3   test  foo
1  1.0 2023-01-01  1.0  3  train  foo

In [9]:
print(df.loc[:, ['A', 'B']])

     A          B
0  1.0 2023-01-01
1  1.0 2023-01-01
2  1.0 2023-01-01
3  1.0 2023-01-01

In [10]:
print(df.iloc[0:2, 0:2])

     A          B
0  1.0 2023-01-01
1  1.0 2023-01-01

# Handling Missing Data

In [17]:
df2 = df.reindex(index=list(range(4)), columns=list(df.columns) + ['G'])

In [18]:
df2

     A          B    C  D      E    F   G
0  1.0 2023-01-01  1.0  3   test  foo NaN
1  1.0 2023-01-01  1.0  3  train  foo NaN
2  1.0 2023-01-01  1.0  3   test  foo NaN
3  1.0 2023-01-01  1.0  3  train  foo NaN

In [20]:
df2

     A          B    C  D      E    F   G
0  1.0 2023-01-01  1.0  3   test  foo NaN
1  1.0 2023-01-01  1.0  3  train  foo NaN
2  1.0 2023-01-01  1.0  3   test  foo NaN
3  1.0 2023-01-01  1.0  3  train  foo NaN

#Data Analysis

In [23]:
df3 = pd.DataFrame({
    'A': ['foo', 'bar', 'foo', 'bar'],
    'B': ['one', 'one', 'two', 'two'],
    'C': np.random.randn(4),
    'D': np.random.randn(4)
})

In [24]:
df3

     A    B         C         D
0  foo  one -0.528412  0.841760
1  bar  one -1.461851  1.519108
2  foo  two -1.185904  1.121476
3  bar  two  0.450444 -0.234776

In [26]:
grouped = df3.groupby('A')
grouped.sum()

          B         C         D
A
bar  onetwo -1.011407  1.284332
foo  onetwo -1.714316  1.963236